#插件基本信息和等级列表配置文件
settings:
  #服务器基本信息
  server: 'Under Worlder 服务器'
  language: 'zh'
  #用户数据保存方式
  storage:
    #可选 Mysql 或者 Sqlite 两种方式
    type: mysql
    #mysql 相关配置
    mysql:
      username: root
      password: '12345678'
      hostname: localhost:3306
      database: minecraft
      table-prefix: jobs_
      verify-server-certificate: false
      use-ssl: false
      auto-reconnect: true
  #自定义等级列表
  guis:
    #魔法祭坛gui
    altar-gui:
      #GUI标题
      title: '魔法祭坛'
      #格子数
      size: 27
      #升级按钮
      upgrade:
        display: '触发魔法进化'
        lores:
        - '当前玩家:{player}'
        - '当前等级:{level}'
        - '================='
        - '下一等级:{nextlevel}'
        - '升级到下一等级需要以下物品'
  levels:
    level1:
      fullname: '&a低级魔人'
      number: 1
      condition:
        mobkill: 5
        money: 10
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level2:
      fullname: '&a中级魔人'
      number: 2
      condition:
        mobkill: 10
        money: 20
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level3:
      fullname: "&a上位魔人"
      number: 3
      condition:
        mobkill: 15
        money: 30
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level4:
      fullname: "&a低级魔将"
      number: 4
      condition:
        mobkill: 20
        money: 40
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level5:
      fullname: "&b中级魔将"
      number: 5
      condition:
        mobkill: 25
        money: 50
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level6:
      fullname: "&b上位魔将"
      number: 6
      condition:
        mobkill: 30
        money: 60
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level7:
      fullname: "&5魔导师"
      number: 7
      condition:
        mobkill: 35
        money: 70
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'
    level8:
      fullname: "&5魔王"
      number: 8
      condition:
        mobkill: 40
        money: 80
        lores:
        - '消耗怪物灵魂(击杀): {mobkill} 个'
        - '消耗金币数量: {money}'