#插件基本信息和等级列表配置文件
settings:
  #服务器基本信息
  server: 'Under Worlder 服务器'
  language: 'zh'
  #用户数据保存方式
  storage:
    #可选 Mysql 或者 Sqlite 两种方式
    type: sqlite
    #mysql 相关配置
    mysql:
      username: root
      password: '12345678'
      hostname: localhost:3306
      database: minecraft
      table-prefix: levels_
      verify-server-certificate: false
      use-ssl: false
      auto-reconnect: true
  #自定义等级列表
  guis:
    #魔法祭坛gui
    altar-gui:

  levels:
    level1:
      fullname: '&a低级魔人'
      number: 1
      maxHealth: 30
      condition:
        mobkill: 5
        money: 10
        items:
        - item1,2
        - bk1,2
    level2:
      fullname: '&a中级魔人'
      number: 2
      maxHealth: 30
      condition:
        mobkill: 10
        money: 20
        items:
        - item1,2
        - bk1,2
    level3:
      fullname: "&a上位魔人"
      maxHealth: 30
      number: 3
      condition:
        mobkill: 15
        money: 30
        items:
        - item1,2
        - bk1,2
    level4:
      fullname: "&a低级魔将"
      number: 4
      maxHealth: 30
      condition:
        mobkill: 20
        money: 40
        items:
        - item1,2
        - bk1,2
    level5:
      fullname: "&b中级魔将"
      number: 5
      maxHealth: 30
      condition:
        mobkill: 25
        money: 50
        items:
        - item1,2
        - bk1,2
    level6:
      fullname: "&b上位魔将"
      number: 6
      maxHealth: 30
      condition:
        mobkill: 30
        money: 60
        items:
        - item1,2
        - bk1,2
    level7:
      fullname: "&5魔导师"
      number: 7
      maxHealth: 30
      condition:
        mobkill: 35
        money: 70
        items:
        - item1,2
        - bk1,2
    level8:
      fullname: "&5魔王"
      number: 8
      maxHealth: 30
      condition:
        mobkill: 40
        money: 80
        items:
        - item1,2
        - bk1,2