#插件基本信息和等级列表配置文件
settings:
  #服务器基本信息
  server: 'Under Worlder 服务器'
  language: 'zh'
  #信息展示的类型none,actionbar,title
  message-showtype: 'actionbar'
  #用户数据保存方式
  storage:
    #可选 Mysql 或者 Sqlite 两种方式
    type: sqlite
    #mysql 相关配置
    mysql:
      username: root
      password: '12345678'
      hostname: localhost:3306
      database: minecraft
      table-prefix: levels_
      verify-server-certificate: false
      use-ssl: false
      auto-reconnect: true
  prefixs:
    "1":
      fullname: '&a魔人'
      mixlevel: 1
    "2":
      fullname: '&a中级魔人'
      mixlevel: 3
    "3":
      fullname: '&a高级魔人'
      mixlevel: 6
    "4":
      fullname: '&a魔将'
      mixlevel: 10
    "5":
      fullname: '&a中位魔将'
      mixlevel: 15
    "6":
      fullname: '&a上位魔将'
      mixlevel: 20
    "7":
      fullname: '&a原初之黑'
      mixlevel: 25
    "8":
      fullname: '&a魔王'
      mixlevel: 30
  wand: 'wand'
  #自定义等级列表
  levels:
    level1:
      fullname:
      number: 1
      maxMagic: 80
      particles:
      - HEART
      condition:
        mobkill: 5
        money: 10
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level2:
      number: 2
      maxMagic: 100
      particles:
      - FIREWORKS_SPARK
      condition:
        mobkill: 10
        money: 20
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level3:
      maxMagic: 120
      number: 3
      particles:
      - FIREWORKS_SPARK
      condition:
        mobkill: 15
        money: 30
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level4:
      number: 4
      maxMagic: 150
      particles:
      - COMPOSTER
      condition:
        mobkill: 20
        money: 40
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level5:
      number: 5
      maxMagic: 170
      particles:
      - SMOKE_LARGE
      condition:
        mobkill: 25
        money: 50
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level6:
      number: 6
      maxMagic: 200
      particles:
      - CLOUD
      condition:
        mobkill: 30
        money: 60
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level7:
      number: 7
      maxMagic: 240
      particles:
      - DRAGON_BREATH
      condition:
        mobkill: 35
        money: 70
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'
    level8:
      number: 8
      maxMagic: 280
      particles:
      - DRIP_WATER
      condition:
        mobkill: 40
        money: 80
        items:
        - item1,2
        - bk1,2
      attributes:
      - '基础血量: 500'